// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgpnnjtwkjyyozvwaltr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRncG5uanR3a2p5eW96dndhbHRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTE4MjAsImV4cCI6MjA2NTQ4NzgyMH0.4bjdU8Ac5LztjtV1JRvkgeSwMX3qw21JH3IUUGvCdxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);